name: dart_i18n
description: A command-line to search for strings marked with i18n() from flutter package localization.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  path: ^1.9.1
  args: ^2.4.1
  analyzer: ^8.1.1
  openai_dart: ^0.6.0+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0